In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

In [17]:
l = [76,,54,65,34,87]

In [19]:
np.mean(l)

63.2

In [21]:
np.mean([64,65,34,87,98,54])

67.0

In [23]:
np.sum([54,6,5,76,34,65])

240

In [25]:
np.sqrt(2)

1.4142135623730951

In [27]:
np.square(67)

4489

In [29]:
# 1d

In [31]:
l = [1,2,3,4,5]

In [35]:
l = np.array(l)

In [37]:
 l

array([1, 2, 3, 4, 5])

In [39]:
np.ndim(l)

1

In [43]:
l2 = [[1,2,3,4,5],[10,20,30,40,50]]

In [45]:
np.array(l2)

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [47]:
l2 = np.array(l2)

In [49]:
np.ndim(l2)

2

In [66]:
l3 = ([[[1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500]]])

In [68]:
l3 = np.array(l3)

In [70]:
l3

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50],
        [100, 200, 300, 400, 500]]])

In [72]:
np.ndim(l3)

3

In [74]:
np.random.randint(1,10,5)

array([6, 4, 5, 4, 5])

In [76]:
np.random.randint(1,50,8)

array([37, 10,  2,  1, 32, 26, 43, 35])

In [78]:
np.random.random([5,3])

array([[0.33641648, 0.15370464, 0.78000102],
       [0.87171657, 0.21218551, 0.61765889],
       [0.15020219, 0.64300026, 0.46003447],
       [0.90019507, 0.02415128, 0.75622934],
       [0.68592204, 0.58275841, 0.15917768]])

In [82]:
np.random.rand(2,2,3)

array([[[0.89852869, 0.42672273, 0.86051613],
        [0.15635635, 0.15864934, 0.67156758]],

       [[0.35552458, 0.92601224, 0.5086454 ],
        [0.54110994, 0.08301779, 0.01393073]]])